# Generated by Django 2.2.5 on 2019-11-10 03:24

from django.db import migrations
from django.conf import settings

LIBRARY_ADMIN_GROUP_NAME = settings.LIBRARY_ADMIN_GROUP_NAME
FUNCTION_NAME = 'trigger_prevent_delete_library_admin'
TRIGGER_NAME = 'prevent_delete_library_admin'


CREATE_GROUP_LIBRARY_ADMIN = f"""
INSERT INTO auth_group (name) VALUES ('{LIBRARY_ADMIN_GROUP_NAME}');

CREATE OR REPLACE FUNCTION {FUNCTION_NAME}() RETURNS trigger LANGUAGE plpgsql AS 
$$
BEGIN
  IF old.name = '{LIBRARY_ADMIN_GROUP_NAME}' THEN
    RAISE EXCEPTION '{{{LIBRARY_ADMIN_GROUP_NAME}}} cannot/should not be modified or deleted.'
    USING HINT='Baaad juju will happen';
  END IF;
  RETURN NULL;
END
$$;

CREATE TRIGGER {TRIGGER_NAME} BEFORE DELETE OR UPDATE ON auth_group
FOR EACH ROW
EXECUTE PROCEDURE {FUNCTION_NAME}();
"""


REVERSE_CREATE_GROUP_LIBRARY_ADMIN = f"""
DROP trigger {TRIGGER_NAME} on auth_group;

DROP function {FUNCTION_NAME};

DELETE FROM auth_group WHERE name='{LIBRARY_ADMIN_GROUP_NAME}'
"""


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_GROUP_LIBRARY_ADMIN,
            REVERSE_CREATE_GROUP_LIBRARY_ADMIN
        ),
    ]
