# Generated by Django 2.2.5 on 2019-11-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191110_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='staff', to='library.Branch'),
        ),
    ]
